### ISSUE TITLE
Use vault https config address

### ISSUE THREAD

**Issue by lovilak** [rundeck-plugins/vault-storage#13]
hello,

Can't connect with selsigned certs with export VAULT_SKIP_VERIFY="true"  in /var/lib/rundeck/.bash_profile or /etc/rundeck/profile.

Thks,

**Comment by ltamaster** [comment]
Hi @lovilak 
Did you try importing the cert to the rundeck's truststore?

**Comment by ltamaster** [comment]
also there is a config property  to do it (on rundeck-config) 

rundeck.storage.provider.1.config.validateSsl=false

**Comment by lovilak** [comment]
rundeck.storage.provider.1.config.validateSsl=false 
is working 
Thanks
