### ISSUE TITLE
Unable to use documented variables in docker hub to activate vault 

### ISSUE THREAD

**Issue by chagaspa** [rundeck-plugins/vault-storage#19]
Hi according to https://hub.docker.com/r/rundeck/rundeck/
to configure the vault storage it should be sufficient (besides copying the plugin to libext) to add the following to the docker yaml :

            RUNDECK_STORAGE_PROVIDER_1_TYPE: vault-storage
            RUNDECK_STORAGE_PROVIDER_1_PATH: /keys/vault
            #RUNDECK_STORAGE_PROVIDER_2_REMOVEPATHPREFIX: "true"
            RUNDECK_STORAGE_PROVIDER_1_CONFIG_SECRETBACKEND: keys
            RUNDECK_STORAGE_PROVIDER_1_CONFIG_ADDRESS: https://vault.xxx.com
            RUNDECK_STORAGE_PROVIDER_1_CONFIG_AUTHBACKEND: token
            #RUNDECK_STORAGE_PROVIDER_2_CONFIG_VALIDATESSL: "false"
            RUNDECK_STORAGE_PROVIDER_1_CONFIG_TOKEN: {{TOKEN}}
            RUNDECK_STORAGE_PROVIDER_1_CONFIG_BEHAVIOUR: vault
            RUNDECK_STORAGE_PROVIDER_1_CONFIG_ENGINEVERSION: 2

What is wrong ?
After successfull image built no option to store keys in vault is available in the gui
we are using vault-plugin 1.3.1 and vault version 1.1.3

Please advise
Regards
Paulo

**Comment by fdansey-ostmodern** [comment]
I think only 'db' or 'file' storage can be configured this way because of the line,
`{% if type == 'db' || type == 'file' %}` in the default template file.
I had success replacing the storage template file in a custom docker image using this:
https://github.com/rundeck-plugins/vault-storage/blob/master/test/docker/dockers/rundeckvault/remco/templates/rundeck-config-storage.properties

**Comment by ltamaster** [comment]
yes, you need to extend the official image and add a custom template 

https://github.com/rundeck-plugins/vault-storage/blob/master/docker/rundeck/Dockerfile

**Comment by chagaspa** [comment]
Thanks for your replies ...
Both workarounds are possible ...but  this seems to be an issue with the rundeck images provided in rundeck docker hub , right ?

**Comment by ltamaster** [comment]
Hi @chagaspa 

It is not an issue, Rundeck has a long list of different plugins, and each plugin has it own settings on `rundeck-config.properties` or `framework.properies`, so it is not possible to have all of them by default. So, the recommended step is extended the official image on your own Dockerfile.

Luis
