### ISSUE TITLE
Support for Namespaces?

### ISSUE THREAD

**Issue by jsfeutz** [rundeck-plugins/vault-storage#21]
Does this plugin support Hashicorp Namespace, i cant seem to to find any info on it.

**Comment by jsfeutz** [comment]
Figured it out:
you can set the namespace as part of the secretBackend path:
rundeck.storage.provider1.config.removePathPrefix=true (this seemed to be required)
rundeck.storage.provider.1.config.secretBackend=ns1/secret

**Comment by ltamaster** [comment]
https://github.com/rundeck-plugins/vault-storage/pull/28
