### ISSUE TITLE
Use vault-storage with existing secrets

### ISSUE THREAD

**Issue by joscha-alisch** [rundeck-plugins/vault-storage#3]
The company I work for uses vault for different tooling - therefore we already have all our secrets there. We recently set up rundeck and wanted to integrate it with vault as well.

I was able to successfully connect rundeck to our vault instance. However - since our secrets don't follow the structure that the plugin expects - it fails when trying to read them. 
The only way to get it to work, is to have a separate directoy within vault that only rundeck uses and to create and update secrets there only through rundeck. 

Sadly, this renders this plugin as unusable for us at the moment, since deduplication of secrets is the main reason for a centralized secret management tool.

Are there any plans to make this plugin more generically usable? For example, it could detect that a secret wasn't created via rundeck and add the metadata to it, or even store the metadata somewhere else?

**Comment by joscha-alisch** [comment]
Here is an example of how a secret looks like for us: ![vault_object](https://user-images.githubusercontent.com/9500791/40510333-abc55df0-5f9c-11e8-8e90-53b003d9b69d.png)

**Comment by gschueler** [comment]
yes, i think this plugin was designed with the original Rundeck key storage use cases and patterns, however it should be possible to enable that kind of usage. For Rundeck, the "storage layer" is a generic data+metadata storage component, and the "key storage" facility is implemented on top of it with attributes like data type stored in the metadata.  Vault is obviously intended for secret storage, so it would make sense to have the plugin treat any values stored in Vault as intended for the "key storage" layer of Rundeck, and perhaps implicitly provide those attributes.  

I'm not that familiar with vault but I understand from your screenshot that you have multiple secure values (password, token, and username) stored under the same "path" within vault.  Rundeck is pretty indifferent about its "key storage paths" used for passwords/private keys.  Really the only requirement is that the `/` separator acts like a directory traversal.  So maybe this vault plugin could add a new "mode" where it interprets a storage path like `some/path/@attribute` as a specific value within the entry.

**Comment by ltamaster** [comment]
Hey @joscha-alisch 

I generated a pre-release here:
https://github.com/rundeck-plugins/vault-storage/releases/tag/1.0.1-SNAPSHOT

If the option "rundeck.storage.provider.1.config.storageBehaviour=vault" is defined on rundeck-config.properties, then the plugin will work without rundeck headers.
So, it this case, existing secrets key/values on vault can be read/update on rundeck.

**Comment by joscha-alisch** [comment]
That's great @ltamaster, thanks. Will try it out later this week :+1:

**Comment by bdfoster** [comment]
I have the same concern, and the latest version of this plugin still requires the password named as 'value' and still requires 'path' and 'prefix' set (which is reflected in the directory of the secret in Vault). I do have the storageBehaviour config attribute set to 'vault'. It would take a while to change all the passwords I have in Vault to the different directory structure. I'd be comfortable with forking and PR'ing this but I guess the way I imagine this working would be a breaking change.

**Comment by lnomine** [comment]
Same here. Having a Rundeck/Vault integration is neat, however we can't afford changing our Vault structure too.

**Comment by ltamaster** [comment]
Hi @bdfoster  @lnomine,

Do you have an example of your vault structure in order to reproduce it?

Thanks
Luis

**Comment by lnomine** [comment]
My secrets are stored in a KV (v1) secret backend named: "apps". Each secret has the name of the app, and inside this secret, several keys like:

```
login: XXXX
password: YYYY
```

**Comment by ltamaster** [comment]
Hi @bdfoster  @lnomine 

It worked for me with the following settings:

> rundeck.storage.provider.1.type=vault-storage
> rundeck.storage.provider.1.path=keys
> **rundeck.storage.provider.1.removePathPrefix=true**
> rundeck.storage.provider.1.config.prefix=app
> rundeck.storage.provider.1.config.address=http://vault:8200
> rundeck.storage.provider.1.config.token=thisisatoken123.
> rundeck.storage.provider.1.config.storageBehaviour=vault

`rundeck.storage.provider.1.removePathPrefix=true` removes the path `keys/`

Please let me know if this helps

![screenshot from 2018-12-06 17-03-30](https://user-images.githubusercontent.com/6034968/49608959-e3eaae80-f978-11e8-9701-fa1c52d8347c.png)
![screenshot from 2018-12-06 17-03-17](https://user-images.githubusercontent.com/6034968/49608960-e3eaae80-f978-11e8-88a3-868967119dac.png)

**Comment by libussa** [comment]
The issue here I think is that it would be nice to not use the default kv store in secret/ (in my case for example it's in version 2 so we can't use it) but have the option to define the base path

**Comment by lovilak** [comment]
hi, I am dealing this aswell and reading its a bit disturbing for me to leave rundeck.storage.provider.1.config.token=thisisatoken123 in clear text in that file.

**Comment by lovilak** [comment]
I've tried to source a unix var from rundeck.storage.provider.1.config.token=$TOKEN which was set from /etc/rundeck/profile but this is not possible.
