### ISSUE TITLE
secretBackend has no effect

### ISSUE THREAD

**Issue by libussa** [rundeck-plugins/vault-storage#8]
I have rundeck.storage.provider.1.config.secretBackend=rundeck in my config, but the plugin is still trying to write in secret/
Is that option working?

**Comment by libussa** [comment]
I believe the issues lies here https://github.com/rundeck-plugins/vault-storage/blob/aa4ae1a624e8ff8500ffd85f555947f468e94ba8/src/main/java/io/github/valfadeev/rundeck/plugin/vault/KeyObjectBuilder.java#L35

where the backend is hardcoded.

**Comment by ltamaster** [comment]
Hi @libussa ,

Yes you are right, I reproduced it and I will send a fix now.

Luis
